# Generated by Django 5.0.2 on 2025-01-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_voice_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_image',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_image',
        ),
    ]
